vim.cmd("set number relativenumber")
vim.cmd("set cursorline")
vim.cmd("set guicursor=a:blinkon5-blinkwait5-blinkoff5")
vim.cmd("set tabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set scrolloff=10")
vim.cmd("set cc=80")
vim.cmd("set clipboard=unnamedplus")
